# permissions for end users to edit pulsarproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulsarproxy-editor-role
rules:
  - apiGroups:
      - pulsar.wirelimited.com
    resources:
      - pulsarproxies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pulsar.wirelimited.com
    resources:
      - pulsarproxies/status
    verbs:
      - get
