# permissions for end users to edit pulsarmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulsarmanager-editor-role
rules:
- apiGroups:
  - pulsar.skulup.com
  resources:
  - pulsarmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pulsar.skulup.com
  resources:
  - pulsarmanagers/status
  verbs:
  - get
