# permissions for end users to view pulsarclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulsarcluster-viewer-role
rules:
  - apiGroups:
      - pulsar.wirelimited.com
    resources:
      - pulsarclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - pulsar.wirelimited.com
    resources:
      - pulsarclusters/status
    verbs:
      - get
