---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
  - apiGroups:
      - pulsar.wirelimited.com
    resources:
      - pulsarclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pulsar.wirelimited.com
    resources:
      - pulsarclusters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - pulsar.wirelimited.com
    resources:
      - pulsarmanagers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pulsar.wirelimited.com
    resources:
      - pulsarmanagers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - pulsar.wirelimited.com
    resources:
      - pulsarproxies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - pulsar.wirelimited.com
    resources:
      - pulsarproxies/status
    verbs:
      - get
      - patch
      - update
