apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRoleName }}
  labels:
  {{- include "pulsar-operator-chart.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - events
      - secrets
      - services
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
    verbs:
      - '*'
  - apiGroups:
      - apps
    resourceNames:
      - pulsar-operator-chart
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - pulsar.pulsar-operator.skulup.com
    resources:
      - '*'
    verbs:
      - '*'
---