name: Test Automation
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        name: Checkout Self Repo

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.2
        with:
          go-version: 1.14

      - name: Install Dependencies
        run: |
          sudo apt-get install make
          curl -L https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
          chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
        env:
          RELEASE_VERSION: v1.0.1

      - name: Run Test
        run: |
          make test

      - name: Generate CRDs
        run: |
          make manifests
          mkdir -p deploy/crds
          cp config/crd/bases/* deploy/crds

      - name: Commit Generated CRDs
        uses: EndBug/add-and-commit@v4
        with:
          add: 'deploy/crds'
          message: 'Autogenerated CRDs from CI'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}